eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    #hostname: service-registry
    prefer-ip-address: true
    

management:
  tracing:
    sampling:
      probability: 1.0
